// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xCxxFx3fvGudarS--T5LxuNadtIGtBI',
    appId: '1:329631896181:web:161fc53345f2bbf9b61e3c',
    messagingSenderId: '329631896181',
    projectId: 'weatherapp-fa6ac',
    authDomain: 'weatherapp-fa6ac.firebaseapp.com',
    storageBucket: 'weatherapp-fa6ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3prlxeB1W7PYjIjxWuNQdEZyF8WqItY',
    appId: '1:329631896181:android:8cdd64625cf9aed5b61e3c',
    messagingSenderId: '329631896181',
    projectId: 'weatherapp-fa6ac',
    storageBucket: 'weatherapp-fa6ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7HhB5_I0NwzAIA_sVm6xGspyhTfjHjw',
    appId: '1:329631896181:ios:ba1f680b9e057130b61e3c',
    messagingSenderId: '329631896181',
    projectId: 'weatherapp-fa6ac',
    storageBucket: 'weatherapp-fa6ac.firebasestorage.app',
    iosBundleId: 'com.example.openweather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7HhB5_I0NwzAIA_sVm6xGspyhTfjHjw',
    appId: '1:329631896181:ios:ba1f680b9e057130b61e3c',
    messagingSenderId: '329631896181',
    projectId: 'weatherapp-fa6ac',
    storageBucket: 'weatherapp-fa6ac.firebasestorage.app',
    iosBundleId: 'com.example.openweather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4xCxxFx3fvGudarS--T5LxuNadtIGtBI',
    appId: '1:329631896181:web:9c6a0330f9e7ce33b61e3c',
    messagingSenderId: '329631896181',
    projectId: 'weatherapp-fa6ac',
    authDomain: 'weatherapp-fa6ac.firebaseapp.com',
    storageBucket: 'weatherapp-fa6ac.firebasestorage.app',
  );
}
